"""remove school_name

Revision ID: 2e748afb4536
Revises: c8f82dae11db
Create Date: 2026-02-22 02:23:09.718693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e748afb4536'
down_revision: Union[str, None] = 'c8f82dae11db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturers', 'school_name')
    op.drop_column('students', 'school_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('school_name', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('lecturers', sa.Column('school_name', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
