"""add multi-school support

Revision ID: a8c641ebde55
Revises: fd5ae738c257
Create Date: 2026-02-22 00:23:02.316617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c641ebde55'
down_revision: Union[str, None] = 'fd5ae738c257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'schools', ['school_id'], ['id'])
    op.add_column('attendance_sessions', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance_sessions', 'schools', ['school_id'], ['id'])
    op.add_column('courses', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'school_id')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_column('attendance_sessions', 'school_id')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'school_id')
    # ### end Alembic commands ###
