"""add school_name to student and lecturer

Revision ID: a8c78d4b97e9
Revises: 6328736d2b01
Create Date: 2026-02-22 00:53:54.354224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c78d4b97e9'
down_revision: Union[str, None] = '6328736d2b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('school_name', sa.String(length=225), nullable=True))
    op.add_column('students', sa.Column('school_name', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'school_name')
    op.drop_column('lecturers', 'school_name')
    # ### end Alembic commands ###
