"""change nullable to False

Revision ID: c8f82dae11db
Revises: a8c78d4b97e9
Create Date: 2026-02-22 02:03:30.448847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f82dae11db'
down_revision: Union[str, None] = 'a8c78d4b97e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance_sessions', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lecturers', 'school_name',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.alter_column('lecturers', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'school_name',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'school_name',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('students', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lecturers', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lecturers', 'school_name',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    op.alter_column('courses', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance_sessions', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
