"""add schools and link to users

Revision ID: fd5ae738c257
Revises: 44cc479d0cb5
Create Date: 2026-02-21 22:58:20.526317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5ae738c257'
down_revision: Union[str, None] = '44cc479d0cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.add_column('lecturers', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lecturers', 'schools', ['school_id'], ['id'])
    op.add_column('students', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'school_id')
    op.drop_constraint(None, 'lecturers', type_='foreignkey')
    op.drop_column('lecturers', 'school_id')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
